backend:
  name: git-gateway
  branch: master 
media_folder: "assets/img"
public_folder: "/img"
collections:
  - name: "english pages"
    label: "English page"
    folder: "src/en/posts/"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}