backend:
  name: git-gateway
  branch: master 
media_folder: "assets/img/surroundings/"
public_folder: "/img/surroundings/"
editor:
  preview: false
collections:
  - name: "english posts"
    label: "Posts (english only)"
    folder: "src/en/posts/"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "page.html"}
      - {label: "Collection", name: "collection", widget: "hidden", default: "posts"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "english pages"
    label: "English pages"
    folder: "src/en/"
    create: true
    filter: {field: "layout", value: "page.html"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page.html"}
      - {label: "Collection", name: "collection", widget: "select", options: ["aboutus", "photos", "surroundings"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
